### ISSUE TITLE
Issue booting vm

### ISSUE THREAD

**Issue by Deepak290** [ContainX/openstack4j#1085]
template: 
```
heat_template_version: 2015-04-30

description: Simple template to deploy a single compute instance

resources:
  my_instance:
    type: OS::Nova::Server
    properties:
      image: cirros
      flavor: m1.tiny 
```
```
 public void Authenticate() {
        OSClientV3 os = OSFactory.builderV3()
                .endpoint("http://***********:5000/v3")
                .credentials("admin", "******", default)
                .authenticate();
    System.out.println(os);

              Stack stack;
        System.out.print(os);
        stack = os.heat().stacks().create(Builders.stack()
                .name("Stack_name")
                .templateFromFile("/home/Deepak/Desktop/demo1.yaml")
                .build());
           System.out.println(stack);}
```

=> issue is is not creating VM , and returning null  (openstack newton and openstack4j 3.0.4 with dep)
outpu =>
org.openstack4j.openstack.internal.OSClientSession$OSClientSessionV3@799c7798
null

=> it's not working with nova "server create" command both are returning null.

List<? extends Flavor> flavors = os.compute().flavors().list();
 System.out.println(flavors);
// Find all running Servers
List<? extends Server> servers = os.compute().servers().list();
 System.out.println(servers);

out/- same
returning null on each line output

Thanks
